SELECT result.WRITER_ID, result.NICKNAME, result.total
FROM (SELECT ub.WRITER_ID, uu.NICKNAME, SUM(ub.PRICE) as total
FROM USED_GOODS_BOARD ub
JOIN USED_GOODS_USER uu
ON ub.WRITER_ID = uu.USER_ID
WHERE ub.STATUS = 'DONE'
GROUP BY ub.WRITER_ID) result
WHERE total>=700000
ORDER BY total ASC;
