# -- 코드를 입력하세요
# -- 조회수가 가장 높은 중고거래 게시물에 대한 첨부파일 경로 조회
SELECT CONCAT('/home/grep/src/',F.BOARD_ID,'/',F.FILE_ID,F.FILE_NAME,F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE F
WHERE F.BOARD_ID = (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
    )
ORDER BY F.FILE_ID DESC;
