SELECT I.ANIMAL_ID,
I.ANIMAL_TYPE,
I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE (O.SEX_UPON_OUTCOME = 'Neutered Male'AND I.SEX_UPON_INTAKE != 'Neutered Male')
OR
(O.SEX_UPON_OUTCOME = 'Spayed Female' AND I.SEX_UPON_INTAKE != 'Spayed Female')



;
